### ISSUE TITLE
EnumProperty capability

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-iot/schemas#14]
As far as I know the gateway implements an `EnumProperty` cabapility. This capability is currently not in the schema. Or is that inherited from some other place?

**Comment by mrstegeman** [comment]
It's not really implemented as a proper capability, but rather just a generic property type. The same could be said for generic string and number properties.

**Comment by mrstegeman** [comment]
That's a fair point. So you envision something like:

| | |
| --- | --- |
| **type** | * |
| **enum** | [_val0_, _val1_, ..., _valN_ ] |

**Comment by freaktechnik** [comment]
Probably, if it supports any type. I'd probably describe the value of the enum prop as something like "Array of strings" or whatever, since the actual values that are selected are the value of the property, and not numeral indexes.

**Comment by mrstegeman** [comment]
We have some solid enum examples in the schemas now.
