### ISSUE TITLE
Add support for integers

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/schemas#16]
In the [Thing Description specification](https://iot.mozilla.org/wot/), the property type can be one of: null, boolean, object, array, number, integer or string. However, in the [schema specification](https://iot.mozilla.org/schemas), integer is never used, only number. Most of the properties in schemas that have `type: number` could be `type: number/integer`. 

_Originally from mozilla-iot/gateway#1467_

**Comment by benfrancis** [comment]
This ambiguity may stem from me being unsure whether "integer" is actually a type supported by JSON Schema. I have seen it used in W3C examples, but the JSON Schema spec only actually seems to mention "number" http://json-schema.org/latest/json-schema-core.html#rfc.section.4.2.1

**Comment by benfrancis** [comment]
From the spec:

> Note that JSON Schema vocabularies are free to define their own extended type system. This should not be confused with the core data model types defined here. As an example, "integer" is a reasonable type for a vocabulary to define as a value for a keyword, but the data model makes no distinction between integers and other numbers.

**Comment by mrstegeman** [comment]
I like integer from a developer point of view, as it allows us to limit numeric inputs further.

**Comment by benfrancis** [comment]
I understand, it's just if it isn't a primitive type supported by JSON Schema (or JavaScript) then how should we go about formally defining that in our specification? It may be simpler to just reference JSON Schema and remove integer as an option?

**Comment by mrstegeman** [comment]
In the JSON Schema validation spec, `integer` seems to be a supported type (emphasis added):
> **6.1.1. type**
>
> The value of this keyword MUST be either a string or an array. If it is an array, elements of the array MUST be strings and MUST be unique.
>
> String values MUST be one of the six primitive types ("null", "boolean", "object", "array", "number", or "string"), **or "integer" which matches any number with a zero fractional part.**
>
> An instance validates if and only if the instance is in any of the sets listed for this keyword. 


Alternatively, if we don't want to use that, we could support `multipleOf`, in addition to `minimum` and `maximum`. This would be more like a step size, so if we set that to an integer value, it would force the value to be an integer. From the spec:
> **6.2.1. multipleOf**
>
> The value of "multipleOf" MUST be a number, strictly greater than 0.
>
> A numeric instance is valid only if division by this keyword's value results in an integer.

**Comment by tomasy** [comment]
mozilla-iot/gateway#1456 is also related. `integer` are today supported in Properties but will not pop up in rule-engine

**Comment by benfrancis** [comment]
@mrstegeman wrote:
> In the JSON Schema validation spec, integer seems to be a supported type (emphasis added):

That's good enough for me! Feel free to submit a pull request adding integer where appropriate. I suppose it's easy enough for a client to accommodate both.
