### ISSUE TITLE
Camera Capability

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/schemas#25]
As a web thing developer I want to expose a camera or video camera as a web thing so that users can capture video, audio and images.

See https://github.com/mozilla-iot/gateway/issues/1438 for implementation in Things Gateway

**Comment by benfrancis** [comment]
OK, starting with a basic proposal:

```
{
  "@context": "https://iot.mozilla.org/schemas/",
  "@type": ["Camera", "VideoCamera"],
  "name": "Web Camera",
  "description": "My web camera",
  "properties": {
    "video": {
      "@type": "VideoProperty",
      "links": [{
        "href": "rtsp://example.com/things/camera/properties/video.mp4",
        "mediaType": "video/mp4"
      }]
    },
    "image": {
      "@type": "ImageProperty",
      "links": [{
        "href": "http://example.com/things/camera/properties/image.jpg",
        "mediaType": "image/jpg"
      }]
    }
  }
}
```

This will require:
* Adding a `links` member to [Property](https://iot.mozilla.org/wot/#property-object) objects in the Thing Description specification, similar to the top level [`links`](https://iot.mozilla.org/wot/#links-member) member
* Adding an `ImageProperty` schema
* Adding a `VideoProperty` schema
* Adding a `Camera` capability with an `ImageProperty`
* Adding a `VideoCamera` capability with a `VideoProperty` and optional `ImageProperty`

This does not include:
* Motion sensor capabilities which can be added with the existing `MotionSensor` capability
* PTZ capabilities which we could add as a separate capability with some kind of move action
* Metadata for the video/audio/image streams/files beyond mediaType, such as resolution
* Any method for requesting a video/audio/image stream/file by particular characteristics
* An action to request a snapshot be taken

Open questions:
* The W3C's latest Thing Description draft uses [`contentType`](https://w3c.github.io/wot-thing-description/#form-serialization-json) for `forms`, but `type` for [`links`](https://w3c.github.io/wot-thing-description/#links-serialization-json). The use of `contentType` rather than `mediaType` is apparently to allow additional parameters to be added (see https://github.com/w3c/wot-thing-description/issues/260). Should we use `type`, `mediaType` or `contentType`?
* If we add `links` to Property objects, should we also support `forms` as per the current W3C draft (which we disagree with) until that is resolved?
* There is no JSON Schema primitive type which is appropriate for a binary file/stream like an audio/video stream or image. Should type be null? Should we extend JSON Schema with a "binary" type? Should the type in fact be "string" and the property be modelled as a URL? I'm inclined to just leave type blank and rely on the mediaType of the link. See also: https://github.com/mozilla-iot/wot/issues/108
* Is it necessary to provide clients with a mechanism to request a video/audio/video stream/file based on certain constraints? (e.g. see related specification for [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) in JavaScript which includes constraints like min and max width and height, whether to get audio and/or video, which camera to use etc.)? An array of links could provide alternative video/audio/image stream/file URLs using different media types, which is a starting point, but currently the above example doesn't provide any additional metadata to help the client make a decision. One way around this would be to make `ImageProperty` and `VideoProperty` a much more complex data structure with type `object` which includes various metadata including URLs, instead of adding the `links` array. Is metadata beyond the `mediaType` actually necessary for a video stream, or will the adaptive streaming specifications adjust resolution etc. accordingly? 
* Should there be an action to request a snapshot be captured and/or stored? How would such an action work? Or is getting an image URL enough?
* Does it make sense to support rtsp:// URLs for video streams? See https://github.com/mozilla-iot/gateway/issues/1438#issuecomment-439494993

**Comment by rzr** [comment]
What about OnOff ? or stream resolution ?

**Comment by mrstegeman** [comment]
I do think this is a good starting point. Some comments below.
> This will require:
> 
>  * Adding a `links` member to [Property](https://iot.mozilla.org/wot/#property-object) objects in the Thing Description specification, similar to the top level [`links`](https://iot.mozilla.org/wot/#links-member) member

It looks like the W3C use `forms` inside of properties. Should we do the same?

> * PTZ capabilities which we could add as a separate capability with some kind of move action

I agree that this can probably wait at the moment, but we should definitely try to get this added soon. It will make cameras far more useful.

> * Metadata for the video/audio/image streams/files beyond mediaType, such as resolution

For now, we can probably just include these as string/number properties until we decide which are truly necessary. It seems like they're primarily informational and can already be determined from the snapshot and/or video stream.

> * Any method for requesting a video/audio/image stream/file by particular characteristics

This seems fine.

> * An action to request a snapshot be taken

See comments further down.

> Open questions:
> 
> * The W3C's latest Thing Description draft uses [`contentType`](https://w3c.github.io/wot-thing-description/#form-serialization-json) for `forms`, but `type` for [`links`](https://w3c.github.io/wot-thing-description/#links-serialization-json). The use of `contentType` rather than `mediaType` is apparently to allow additional parameters to be added (see [w3c/wot-thing-description#260](https://github.com/w3c/wot-thing-description/issues/260)). Should we use `type`, `mediaType` or `contentType`?

The arguments for `contentType` make sense to me.

> * If we add `links` to Property objects, should we also support `forms` as per the current W3C draft (which we disagree with) until that is resolved?

What's the difference, exactly?

> * There is no JSON Schema primitive type which is appropriate for a binary file/stream like an audio/video stream or image. Should type be null? Should we extend JSON Schema with a "binary" type? Should the type in fact be "string" and the property be modelled as a URL? I'm inclined to just leave type blank and rely on the mediaType of the link. See also: [mozilla-iot/wot#108](https://github.com/mozilla-iot/wot/issues/108)

I agree, these can just be null properties with only a `links`/`forms` array.

> * Is it necessary to provide clients with a mechanism to request a video/audio/video stream/file based on certain constraints? (e.g. see related specification for [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) in JavaScript which includes constraints like min and max width and height, whether to get audio and/or video, which camera to use etc.)? An array of links could provide alternative video/audio/image stream/file URLs using different media types, which is a starting point, but currently the above example doesn't provide any additional metadata to help the client make a decision. One way around this would be to make `ImageProperty` and `VideoProperty` a much more complex data structure with type `object` which includes various metadata including URLs, instead of adding the `links` array. Is metadata beyond the `mediaType` actually necessary for a video stream, or will the adaptive streaming specifications adjust resolution etc. accordingly?

I'm not so sure about this. Cameras can only be capturing in a single mode at any time, but can be viewed by many different clients. I think a better alternative is to include an enum with several different preset modes that can be selected.

> * Should there be an action to request a snapshot be captured and/or stored? How would such an action work? Or is getting an image URL enough?

ONVIF cameras have a "snapshot URL". When you browse to it, it will take a snapshot and return it. That's a little bit different from how our properties typically work, but since the ImageProperty doesn't have a value, I think it's reasonable to just include a single URL where the image can be fetched without need for an action.

> * Does it make sense to support rtsp:// URLs for video streams? See [mozilla-iot/gateway#1438 (comment)](https://github.com/mozilla-iot/gateway/issues/1438#issuecomment-439494993)

I do still think this is the way to go. RTSP is the de facto standard for IP cameras. Those streams can easily be opened by a variety of software. For web purposes, it's easy enough for us to translate to MPEG-DASH, HLS, or something else.

**Comment by benfrancis** [comment]
@rzr wrote:
> What about OnOff ? or stream resolution ?

What would the `OnOffProperty` do exactly? Is it not enough to start a video stream when a client requests it? See above comments regarding metadata around stream resolution.

@mrstegeman wrote:
> What's the difference [between links and forms], exactly?

The topic of [links vs. forms](https://github.com/w3c/wot-thing-description/issues/88) has been the subject of significant debate at the W3C which is difficult to summarise here.

Basically the `forms` member of Property, Action and Event objects has been by the W3C Working Group's [Protocol Binding Templates](https://w3c.github.io/wot-binding-templates/) specification to provide declarative protocol bindings for any arbitrary IoT protocol, to avoid the need for concrete protocol specifications like our proposed REST & WebSocket APIs.

In the past this theoretically included bindings for non-web and even non-Internet protocols. Lately it has settled on a more reduced scope of any protocols which support URIs (which is good), but the forms approach still uses quite a complex design based around "hypermedia controls" and declarative protocol bindings, rather than simple [web linking](https://tools.ietf.org/html/rfc5988). For simple examples, it's basically identical to links. But it also supports much more complex use cases, like describing how to directly talk to devices using non-web protocols like MQTT and defining different message types and payload formats for reading/writing properties, requesting actions, subscribing to events etc. inside the Thing Description itself.

Given we currently only support HTTP & WebSockets with concrete protocol bindings, the only features we actually need are `href`, `contentType`, and `rel` which comprise a "link", exactly like the top level [`links`](https://iot.mozilla.org/wot/#links-member) member. We could just call those "forms" to be compliant with the W3C spec, but personally I don't think the analogy of forms works well and I think the declarative protocol bindings template approach is flawed and won't scale. Or we could support the terms `links` and `forms` interchangeably (with that same subset of features) until the debate is fully resolved.

What does everyone else think?

**Comment by benfrancis** [comment]
See also https://github.com/mozilla-iot/wot/issues/79

**Comment by rzr** [comment]
well I thought a privacy by design camera could be turned off regardless if there are any viewers

**Comment by benfrancis** [comment]
> well I thought a privacy by design camera could be turned off regardless if there are any viewers

Hmm, I'm not sure how that would work. If there are multiple users accessing the camera over the web at the same time, who gets to decide whether the camera is on or off? It would be better to put a physical off switch on the camera itself.

**Comment by mrstegeman** [comment]
Maybe we should add support for a motorized camera cover. :smile:

**Comment by benfrancis** [comment]
@mrstegeman wrote:
> I agree, these can just be null properties with only a links/forms array.

I ran this by the W3C WG and it turns out they already reached the same conclusion https://github.com/w3c/wot-thing-description/issues/305

**Comment by kgiori** [comment]
> > well I thought a privacy by design camera could be turned off regardless if there are any viewers
> 
> Hmm, I'm not sure how that would work. If there are multiple users accessing the camera over the web at the same time, who gets to decide whether the camera is on or off? It would be better to put a physical off switch on the camera itself.

I agree that once ACLs are available, I'd want the ability to control when a video stream or photo capture is possible. Using geolocation automation, that might mean to disable it anytime I'm home. I find it creepy to have my laptop camera pointed at my face whenever the green light is on, even if I'm not on a video call nor recording anything. And think about all the "hacked" into web cams that have been exposed to the Internet, showing people in their homes who have no idea their stream is live. I find that quite unfortunate. 

Instead of on/off, how about an "enable/disable" option?

Would enabled

**Comment by benfrancis** [comment]
Enable/disable just sounds like another name for on/off. Either way the use case described sounds like a permissions issue about choosing who has access to a camera device. If a user has access to the device to view its video stream, then they would also have access to its enabled property to turn it back on again, so it would serve no function. Revoking permission to the camera or its video property would have the effect as setting an enabled property to false.

This may be a requirement for a UI feature of a web thing or web thing gateway implementation to make it easy to temporarily revoke access to other users, but I don't think that requires a dedicated property in this low level data schema. We don't have an enable/disable property for any other type of sensor like motion sensors or door sensors.
