### ISSUE TITLE
"EnergyMonitor" is missing phase / power factor

### ISSUE THREAD

**Issue by jernst** [mozilla-iot/schemas#28]
Contrary to popular opinion :-) Wattage does not equal Voltage times Current. In AC, the only thing we know is that Wattage is not larger than Voltage times Current and not smaller than -Voltage times Current. Where it is in the interval depends on the power factor (or the relative phase of Voltage and Current).

So: add Power Factor as a property. Devices such as the Iotawatt directly report on it, see "pf:" in this screen shot: https://iotawatt.com/assets/img/screenshot%20status.png

https://en.wikipedia.org/wiki/Power_factor

**Comment by freaktechnik** [comment]
Alternatively the device could report real power and whatever the other power is called. However that only makes the calculations based on power factor more annoying, though it should complete the system, iirc.

**Comment by jernst** [comment]
Depending on what the purpose of the IoT system is, power factors may either be irrelevant or crucial, so a general-purpose spec should handle them well IMHO. For example, in the worst-case scenario (power factor close to 0), real power consumed by, say, a house, or a big consumer, may be close to zero, while the current flowing is melting the wires :-)
