### ISSUE TITLE
NotificationAction

### ISSUE THREAD

**Issue by tim-hellhake** [mozilla-iot/schemas#43]
As a user i would like trigger a notification on my device.
The notification may contain a message of type string.
It may also contain an urgency level like `INFO` or `ALERT`.

**Comment by rzr** [comment]
Could make sense, what do you have in mind ? Like a popup or log entry ?

May this relate to some (naives) experiments made using properties at:
https://github.com/rzr/mastodon-lite/tree/master/example

**Comment by raidnet-ms** [comment]
What about [Mozilla notification API?](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API). In this way they would be shown on the operating system GUI of the client running the web browser.

**Comment by tim-hellhake** [comment]
> Could make sense, what do you have in mind ? Like a popup or log entry ?

Actually something similar to what you have done.
I'm currently working on an addon to send slack notifications.
But i think actions are the appropriate choice for that.

**Comment by tim-hellhake** [comment]
> What about [Mozilla notification API?](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API). In this way they would be shown on the operating system GUI of the client running the web browser.

It would be nice to have them but i think this would an ui thing.
Im talking about connection messaging services and devices which could present you a notification.

**Comment by mrstegeman** [comment]
This seems like it’s probably a duplicate of https://github.com/mozilla-iot/gateway/issues/1758

**Comment by tim-hellhake** [comment]
For webservices this is true.
However, there are also devices which provide a notification mechanism.

**Comment by benfrancis** [comment]
> However, there are also devices which provide a notification mechanism.

Can you provide examples?

This doesn't seem like an action performed on a physical device itself, rather a potential output of a rule performed with an external software service as a result of a change in state of the device.

**Comment by tim-hellhake** [comment]
https://lametric.com

**Comment by tim-hellhake** [comment]
There would be one adapter which would discover n devices.

**Comment by benfrancis** [comment]
Some people have built web things with an LCD which has a string property you can set to display the string on the screen.

Perhaps I'm missing something but is the any particular reason this should be an action rather than a property?

**Comment by mrstegeman** [comment]
Notifications are typically temporary, so it makes sense for it to be an action. You could set a notification level and length. This seems kind of like an extension to the Alarm capability, in a way.

**Comment by tim-hellhake** [comment]
Additionally, they might be queued.
Even if you could read the display contents it's not guaranteed that it's your notification.

**Comment by benfrancis** [comment]
OK, yes that is sounding more like an action.

A few of things to think about:
1. The name of an action is usually contains a verb
2. An action is usually something carried out on a device, rather than carried out on a user by a device (i.e. the device is the object, not the subject)
3. The action schema should be generic enough to be widely applicable to a range of devices

So what's a good name for the kinds of use cases you have in mind? Maybe something like DisplayMessageAction?

And what kind of input should a Thing expect to the action? Just a simple string? Or is there some other input which would be widely applicable enough to be part of the schema? (e.g. For "level", are "info" and "alert" too arbitrary? We had a similar discussion about the [AlarmCapability](https://github.com/mozilla-iot/schemas/pull/36).

**Comment by tim-hellhake** [comment]
How about `NotifyAction`?

I think the `message` parameter should be required.
As for the `urgency` level: The [Desktop Notifications Specification](https://developer.gnome.org/notification-spec) specifies three urgency levels:
- Low
- Normal
- Alert

**Comment by benfrancis** [comment]
> How about NotifyAction?

I would argue that would make the user the object rather than the device.

> I think the message parameter should be required

Makes sense.

Note that [Web Notifications](https://developer.mozilla.org/en-US/docs/Web/API/notification) have a title and a body (amongst many other types of metadata).

**Comment by tim-hellhake** [comment]
I see that's what you meant by 
> the device is the object
Well then `DisplayMessageAction` or better `DisplayNotificationAction` would be fine.

**Comment by tim-hellhake** [comment]
Fixed by https://github.com/mozilla-iot/gateway/issues/1758
