### ISSUE TITLE
Is this superseded by WoT Thing Description

### ISSUE THREAD

**Issue by white-gecko** [mozilla-iot/schemas#63]
This this specification superseded by the [Web of Things (WoT) Thing Description
W3C Candidate Recommendation](https://www.w3.org/TR/wot-thing-description/) or is it still developed?

**Comment by mrstegeman** [comment]
Our [spec](https://github.com/mozilla-iot/wot) still diverges from the W3C version right now. We're working to resolve those issues.

This repo, however, complements both. These are standalone schemas which can be used by either version of the spec.
