### ISSUE TITLE
PushButton Capability Schema

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/schemas#8]
As a device developer I want to tell a Web of Things client that my device acts as a push button.

Example Thing Description:
```
{
  "@context": "https://iot.mozilla.org/schemas",
  "@type": ["PushButton"],
  "name": "Push Button",
  "properties": {
    "pushed": {
      "@type": "PushedProperty",
      "type": "boolean"
    }
  }
}
```

**Comment by rzr** [comment]
does this replace the switch ?
because In my world a button stay in original position if not pressed (due to spring) ?

I also implemented a toggle button, that toggle its "internal state" on each press action.

**Comment by rzr** [comment]
Ok we're aligned

https://github.com/mozilla-iot/schemas/pull/7

<p>A momenetary switch which can be pressed and returns to an un-pressed state when released.</p>
